spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:mem:jactdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jact:
  enabled: true
  initial-page: "/"
  window-title: "JACT M3 Task Manager"
  window-width: 960
  window-height: 640
